name: telegram message
on:
  pull_request:
    types: [opened, reopened, edited, ready_for_review]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: send telegram message on pull request
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          format: markdown
          disable_web_page_preview: true
          message: |
            Новый PR, [нужно ревью](https://github.com/Videot4pe/the-soap/pull/${{ github.event.number }})!
          
